export const products = [
  { id: 1, name: "Chicken Breast" },
  { id: 2, name: "Chicken Wings" },
  { id: 3, name: "Chicken Drumsticks" },
  { id: 4, name: "Chicken Curry Cut" },
  { id: 5, name: "Chicken Boneless" },
  { id: 6, name: "Chicken Thigh" },
  { id: 7, name: "Chicken Liver" },
  { id: 8, name: "Chicken Mince" },
  { id: 9, name: "Chicken Lollipop" },
  { id: 10, name: "Chicken Soup Bones" },

  { id: 11, name: "Mutton Curry Cut" },
  { id: 12, name: "Mutton Boneless" },
  { id: 13, name: "Mutton Keema" },
  { id: 14, name: "Mutton Chops" },
  { id: 15, name: "Mutton Liver" },
  { id: 16, name: "Mutton Ribs" },
  { id: 17, name: "Mutton Brain" },
  { id: 18, name: "Mutton Shoulder" },
  { id: 19, name: "Mutton Leg" },
  { id: 20, name: "Mutton Soup Pieces" },

  { id: 21, name: "Fish Fillet" },
  { id: 22, name: "Rohu Fish" },
  { id: 23, name: "Katla Fish" },
  { id: 24, name: "Salmon Fish" },
  { id: 25, name: "Tuna Fish" },
  { id: 26, name: "Pomfret Fish" },
  { id: 27, name: "Surmai Fish" },
  { id: 28, name: "Hilsa Fish" },
  { id: 29, name: "Tilapia Fish" },
  { id: 30, name: "Fish Curry Cut" },

  { id: 31, name: "Prawns Small" },
  { id: 32, name: "Prawns Medium" },
  { id: 33, name: "Prawns Jumbo" },
  { id: 34, name: "Tiger Prawns" },
  { id: 35, name: "Shrimps Cleaned" },
  { id: 36, name: "Prawns Deveined" },
  { id: 37, name: "Garlic Butter Prawns" },
  { id: 38, name: "Spicy Prawns" },
  { id: 39, name: "Frozen Prawns" },
  { id: 40, name: "Prawns Curry Cut" },

  { id: 41, name: "Eggs Pack 6" },
  { id: 42, name: "Eggs Pack 12" },
  { id: 43, name: "Eggs Pack 30" },
  { id: 44, name: "Brown Eggs Pack" },
  { id: 45, name: "Organic Eggs" },
  { id: 46, name: "Duck Eggs" },
  { id: 47, name: "Quail Eggs" },
  { id: 48, name: "Farm Fresh Eggs" },
  { id: 49, name: "Omega Eggs" },
  { id: 50, name: "Desi Eggs" },

  { id: 51, name: "Chicken Sausages" },
  { id: 52, name: "Chicken Nuggets" },
  { id: 53, name: "Chicken Seekh Kebab" },
  { id: 54, name: "Chicken Tikka" },
  { id: 55, name: "Chicken Burger Patty" },
  { id: 56, name: "Chicken Popcorn" },
  { id: 57, name: "Chicken Salami" },
  { id: 58, name: "Chicken Ham" },
  { id: 59, name: "Chicken Meatballs" },
  { id: 60, name: "Chicken Cutlets" },

  { id: 61, name: "Mutton Seekh Kebab" },
  { id: 62, name: "Mutton Shami Kebab" },
  { id: 63, name: "Mutton Burger Patty" },
  { id: 64, name: "Mutton Meatballs" },
  { id: 65, name: "Mutton Salami" },
  { id: 66, name: "Mutton Tikka" },
  { id: 67, name: "Mutton Kofta" },
  { id: 68, name: "Mutton Cutlets" },
  { id: 69, name: "Mutton Curry Ready Mix" },
  { id: 70, name: "Mutton Biryani Cut" },

  { id: 71, name: "Fish Fingers" },
  { id: 72, name: "Fish Cutlets" },
  { id: 73, name: "Fish Nuggets" },
  { id: 74, name: "Fish Burger Patty" },
  { id: 75, name: "Fish Tikka" },
  { id: 76, name: "Fish Fry Pieces" },
  { id: 77, name: "Fish Pakora" },
  { id: 78, name: "Fish Curry Ready Mix" },
  { id: 79, name: "Fish Biryani Cut" },
  { id: 80, name: "Fish Popcorn" },

  { id: 81, name: "Ready to Cook Chicken Curry" },
  { id: 82, name: "Ready to Cook Butter Chicken" },
  { id: 83, name: "Ready to Cook Chicken Biryani" },
  { id: 84, name: "Ready to Cook Chicken Tikka Masala" },
  { id: 85, name: "Ready to Cook Chicken Korma" },
  { id: 86, name: "Ready to Cook Mutton Curry" },
  { id: 87, name: "Ready to Cook Mutton Biryani" },
  { id: 88, name: "Ready to Cook Mutton Korma" },
  { id: 89, name: "Ready to Cook Fish Curry" },
  { id: 90, name: "Ready to Cook Fish Fry" },

  { id: 91, name: "Marinated Chicken Tikka" },
  { id: 92, name: "Marinated Chicken Wings" },
  { id: 93, name: "Marinated Chicken Drumsticks" },
  { id: 94, name: "Marinated Mutton Chops" },
  { id: 95, name: "Marinated Fish Fillet" },
  { id: 96, name: "Marinated Prawns" },
  { id: 97, name: "Spicy Chicken Curry Cut" },
  { id: 98, name: "Classic Chicken Curry Cut" },
  { id: 99, name: "Premium Mutton Boneless" },
  { id: 100, name: "Fresh Fish Combo Pack" }
];

export const BASE_URL = process.env.NEXT_PUBLIC_API_BASE_URL;